### ISSUE TITLE
Please consider changing a name to something more meaningful 

### ISSUE THREAD

**Issue by WojMam** [dirishere/PythonChallenges#1]
https://github.com/dirishere/PythonChallenges/blob/42f7b5e3851036f13b429539efda053569248ea1/python_challenge_02/python_challenge_02.py#L4

**Comment by dirishere** [comment]
👍

**Comment by dirishere** [comment]
Fixed! 
[python_challenge_02/python_challenge_02.py](https://github.com/dirishere/PythonChallenges/blob/45f68f47d1ab518cf185ebfe6e06147b94bbd234/python_challenge_02/python_challenge_02.py)
